2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Configure stats pid to 2460
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jinya\.config\wandb\settings
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Loading settings from D:\MScDataSparqProject\Supporting_files\wandb\settings
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'datasparq', 'entity': 'datasparq', 'root_dir': 'D:\\MScDataSparqProject\\Supporting_files', 'sweep_id': '65gltdwl', 'run_id': '32r78wm4', 'sweep_param_path': 'D:\\MScDataSparqProject\\Supporting_files\\wandb\\sweep-65gltdwl\\config-32r78wm4.yaml'}
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Supporting_files\\main_test.py', 'program_abspath': 'd:\\MScDataSparqProject\\Supporting_files\\main_test.py', 'program': 'd:\\MScDataSparqProject\\Supporting_files\\main_test.py'}
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_init.py:_log_setup():527] Logging user logs to D:\MScDataSparqProject\Supporting_files\wandb\run-20240327_113230-32r78wm4\logs\debug.log
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_init.py:_log_setup():528] Logging internal logs to D:\MScDataSparqProject\Supporting_files\wandb\run-20240327_113230-32r78wm4\logs\debug-internal.log
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_init.py:init():567] calling init triggers
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_init.py:init():574] wandb.init called with sweep_config: {'batch_size': 64, 'epochs': 20, 'learning_rate': 0.025890232366038105}
config: {}
2024-03-27 11:32:30,716 INFO    Thread-17 (_run_job):2460 [wandb_init.py:init():612] wandb.init() called when a run is still active
2024-03-27 11:32:31,759 ERROR   Thread-17 (_run_job):2460 [wandb_init.py:init():1215] error
Traceback (most recent call last):
  File "d:\py\Lib\site-packages\wandb\sdk\wandb_init.py", line 1187, in init
    run = wi.init()
          ^^^^^^^^^
  File "d:\py\Lib\site-packages\wandb\sdk\wandb_init.py", line 613, in init
    with telemetry.context() as tel:
  File "d:\py\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "d:\py\Lib\site-packages\wandb\sdk\wandb_run.py", line 763, in _telemetry_callback
    self._telemetry_flush()
  File "d:\py\Lib\site-packages\wandb\sdk\wandb_run.py", line 774, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "d:\py\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "d:\py\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "d:\py\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "d:\py\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "d:\py\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "d:\py\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
